// Global exercise library (coachId = null). [name, muscleGroups, equipment]
export const EXERCISES: [string, string[], string[]][] = [
  ["Back Squat", ["quads", "glutes"], ["barbell", "rack"]],
  ["Front Squat", ["quads", "core"], ["barbell", "rack"]],
  ["Goblet Squat", ["quads", "glutes"], ["dumbbell"]],
  ["Bulgarian Split Squat", ["quads", "glutes"], ["dumbbell", "bench"]],
  ["Walking Lunge", ["quads", "glutes"], ["dumbbell"]],
  ["Reverse Lunge", ["quads", "glutes"], ["bodyweight"]],
  ["Step-Up", ["quads", "glutes"], ["dumbbell", "box"]],
  ["Leg Press", ["quads", "glutes"], ["machine"]],
  ["Leg Extension", ["quads"], ["machine"]],
  ["Box Jump", ["quads", "glutes"], ["box"]],
  ["Conventional Deadlift", ["hamstrings", "glutes", "back"], ["barbell"]],
  ["Romanian Deadlift", ["hamstrings", "glutes"], ["barbell"]],
  ["Single-Leg Romanian Deadlift", ["hamstrings", "glutes"], ["dumbbell"]],
  ["Trap Bar Deadlift", ["quads", "glutes", "back"], ["trap bar"]],
  ["Hip Thrust", ["glutes"], ["barbell", "bench"]],
  ["Glute Bridge", ["glutes"], ["bodyweight"]],
  ["Kettlebell Swing", ["glutes", "hamstrings"], ["kettlebell"]],
  ["Lying Leg Curl", ["hamstrings"], ["machine"]],
  ["Nordic Hamstring Curl", ["hamstrings"], ["bodyweight"]],
  ["Good Morning", ["hamstrings", "back"], ["barbell"]],
  ["Standing Calf Raise", ["calves"], ["machine"]],
  ["Seated Calf Raise", ["calves"], ["machine"]],
  ["Bench Press", ["chest", "triceps", "shoulders"], ["barbell", "bench"]],
  ["Incline Bench Press", ["chest", "shoulders"], ["barbell", "bench"]],
  ["Dumbbell Bench Press", ["chest", "triceps"], ["dumbbell", "bench"]],
  ["Incline Dumbbell Press", ["chest", "shoulders"], ["dumbbell", "bench"]],
  ["Push-Up", ["chest", "triceps", "core"], ["bodyweight"]],
  ["Dip", ["chest", "triceps"], ["dip bars"]],
  ["Cable Fly", ["chest"], ["cable"]],
  ["Dumbbell Fly", ["chest"], ["dumbbell", "bench"]],
  ["Overhead Press", ["shoulders", "triceps"], ["barbell"]],
  ["Seated Dumbbell Shoulder Press", ["shoulders", "triceps"], ["dumbbell", "bench"]],
  ["Arnold Press", ["shoulders"], ["dumbbell"]],
  ["Lateral Raise", ["shoulders"], ["dumbbell"]],
  ["Rear Delt Fly", ["shoulders", "upper back"], ["dumbbell"]],
  ["Face Pull", ["shoulders", "upper back"], ["cable"]],
  ["Pull-Up", ["lats", "biceps"], ["pull-up bar"]],
  ["Chin-Up", ["lats", "biceps"], ["pull-up bar"]],
  ["Lat Pulldown", ["lats", "biceps"], ["cable"]],
  ["Barbell Row", ["back", "lats"], ["barbell"]],
  ["Dumbbell Row", ["back", "lats"], ["dumbbell", "bench"]],
  ["Seated Cable Row", ["back", "lats"], ["cable"]],
  ["Chest-Supported Row", ["back"], ["dumbbell", "bench"]],
  ["Inverted Row", ["back", "biceps"], ["bar", "rack"]],
  ["Straight-Arm Pulldown", ["lats"], ["cable"]],
  ["Shrug", ["traps"], ["dumbbell"]],
  ["Barbell Curl", ["biceps"], ["barbell"]],
  ["Dumbbell Curl", ["biceps"], ["dumbbell"]],
  ["Hammer Curl", ["biceps", "forearms"], ["dumbbell"]],
  ["Preacher Curl", ["biceps"], ["ez bar", "bench"]],
  ["Triceps Pushdown", ["triceps"], ["cable"]],
  ["Overhead Triceps Extension", ["triceps"], ["dumbbell"]],
  ["Skull Crusher", ["triceps"], ["ez bar", "bench"]],
  ["Close-Grip Bench Press", ["triceps", "chest"], ["barbell", "bench"]],
  ["Plank", ["core"], ["bodyweight"]],
  ["Side Plank", ["core", "obliques"], ["bodyweight"]],
  ["Dead Bug", ["core"], ["bodyweight"]],
  ["Bird Dog", ["core", "lower back"], ["bodyweight"]],
  ["Hanging Leg Raise", ["core"], ["pull-up bar"]],
  ["Cable Crunch", ["core"], ["cable"]],
  ["Russian Twist", ["obliques"], ["medicine ball"]],
  ["Pallof Press", ["core", "obliques"], ["cable"]],
  ["Ab Wheel Rollout", ["core"], ["ab wheel"]],
  ["Farmer's Carry", ["forearms", "traps", "core"], ["dumbbell"]],
  ["Suitcase Carry", ["core", "obliques"], ["kettlebell"]],
  ["Turkish Get-Up", ["shoulders", "core"], ["kettlebell"]],
  ["Kettlebell Goblet Clean", ["full body"], ["kettlebell"]],
  ["Power Clean", ["full body"], ["barbell"]],
  ["Thruster", ["full body"], ["barbell"]],
  ["Burpee", ["full body"], ["bodyweight"]],
  ["Mountain Climber", ["core", "shoulders"], ["bodyweight"]],
  ["Jumping Jack", ["full body"], ["bodyweight"]],
  ["Jump Rope", ["calves", "conditioning"], ["jump rope"]],
  ["Rowing Machine", ["conditioning"], ["rower"]],
  ["Assault Bike", ["conditioning"], ["air bike"]],
  ["Treadmill Run", ["conditioning"], ["treadmill"]],
  ["Sled Push", ["quads", "conditioning"], ["sled"]],
  ["Battle Rope Waves", ["shoulders", "conditioning"], ["battle rope"]],
  ["Medicine Ball Slam", ["full body"], ["medicine ball"]],
  ["Band Pull-Apart", ["upper back", "shoulders"], ["resistance band"]],
  ["Hip Flexor Stretch", ["mobility"], ["bodyweight"]],
  ["World's Greatest Stretch", ["mobility"], ["bodyweight"]],
];
